### ISSUE TITLE
Seems like 'false' is an invalid token

### ISSUE THREAD

**Issue by gamedevsam** [yhslai/haxetoml#3]
I got this error when I tried to assign a bool to false:

Line 2 Character 1: Invalid Token 'false' at haxetoml::TomlParser/InvalidToken()[\source\lib\toml\src\haxetoml\TomlParser.hx:337]

**Comment by gamedevsam** [comment]
Found the problem, it was a an issue with the regular expression for boolean:

was:
`{ type: TokenType.TkBoolean, ereg: ~/^true|false/},`
fixed:
`{ type: TokenType.TkBoolean, ereg: ~/^true|^false/},`

it was missing the `^` before the false

**Comment by yhslai** [comment]
It's not the reason, the real problem is my matching order is wrong so that it deems 'false' as a key(not boolean).
But sadly and reluctantly, the regexp is wrong too. Thanks for pointing out these two bugs.

I think I fixed it in v0.1.3. If you have time please try out.

(seems I should prepare some comprehensive test files and unit tests... but I truly have no time recently)

**Comment by gamedevsam** [comment]
works. thx
